import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { documentApi } from "../api";
import { useProjectCtx } from "../hooks/useProject";
import { Badge, Card, CardHeader, Loading, formatDateTime } from "../components/ui";
import { ArrowRight, Bot, RefreshCw, Send, ShieldCheck } from "lucide-react";

const TONE = { BLOCKED:"rose", OPEN:"rose", FAILED:"rose", RECHECK_REQUIRED:"amber", UNKNOWN:"amber", UNAVAILABLE:"amber", UNBOUND:"gray", WAITING_ON_OWNER:"blue", ACTION_IN_PROGRESS:"blue", EXECUTING:"blue", RESOLVED:"emerald", SUCCEEDED:"emerald", OK:"emerald", CLEAR:"emerald" };
const QUERIES = [["FOCUS_TODAY","Focus today"],["PROJECT_STATUS","Project status"],["WHAT_CHANGED","What changed?"],["WHAT_IS_BLOCKED","What is blocked?"],["WHAT_IS_UNRESOLVED","What is unresolved?"]];

function State({ value }) {
  const text = typeof value === "object" ? `${value.active || 0} active · ${value.waiting || 0} waiting` : value || "UNKNOWN";
  return <Badge tone={TONE[String(value)] || "gray"}>{String(text).replaceAll("_", " ")}</Badge>;
}

export default function ProjectHome() {
  const { project } = useProjectCtx();
  const [center,setCenter] = useState(null), [error,setError] = useState(null);
  const [busy,setBusy] = useState(false), [copilot,setCopilot] = useState(null);
  const [queryType,setQueryType] = useState("FOCUS_TODAY"), [question,setQuestion] = useState("What should I focus on today?");
  async function load() { setError(null); try { setCenter(await documentApi.commandCenter(project.id)); } catch (e) { setError(e); } }
  useEffect(() => { if (project?.id) load(); }, [project?.id]);
  async function ask(type=queryType) { setBusy(true); setCopilot(null); try { setCopilot(await documentApi.projectCopilot(project.id,{query_type:type,question,user_role:null})); } catch(e) { setCopilot({status:"UNAVAILABLE",message:e.message||String(e),focus_items:[]}); } finally { setBusy(false); } }
  if (!project || (!center && !error)) return <Loading />;
  const evidence = Object.fromEntries((center?.copilot_context?.evidence || []).map(x => [x.evidence_id,x]));
  const active=center?.resolution_summary?.active||[], resolved=center?.resolution_summary?.recently_resolved||[], routes=center?.action_summary?.routes||[], health=center?.health||{};
  const resolutionIntel=center?.resolution_intelligence||{}, resolutionFocus=resolutionIntel.focus_items||[];
  const brief=center?.daily_briefing;
  async function markReviewed() { if(!brief?.mark_reviewed) return; setBusy(true); try { await documentApi.markBriefingReviewed(project.id,brief.mark_reviewed); await load(); } catch(e) { setError(e); } finally { setBusy(false); } }
  return <main className="space-y-5" aria-labelledby="command-center-title">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 id="command-center-title" className="text-xl font-bold">{project.name} Command Center</h1><p className="mt-1 text-sm text-gray-500">Current project state, attention, impact, action, and resolution—composed from owner truth.</p></div><button onClick={load} className="inline-flex items-center gap-1 rounded border bg-white px-3 py-2 text-sm"><RefreshCw size={14}/> Refresh truth</button></header>
    {error && <Card className="p-4 text-sm text-rose-700">Command Center unavailable: {error.message||String(error)}</Card>}
    {center && <>
      {brief&&<Briefing brief={brief} onReviewed={markReviewed} busy={busy}/>}
      <section aria-label="Project Health" className="grid grid-cols-2 gap-3 lg:grid-cols-5">{[["Delivery",health.delivery],["QA",health.qa],["Infra",health.infra],["Governance",health.governance],["Resolution",health.resolution]].map(([label,value])=><Card key={label} className="p-3"><h2 className="text-xs font-semibold uppercase text-gray-500">{label}</h2><div className="mt-2"><State value={value}/></div></Card>)}</section>
      <Card className="border-amber-200"><CardHeader title="Resolution Focus" subtitle="Why work is unresolved, what authoritative truth would resolve it, and the safest supported next step."/><div className="grid grid-cols-4 gap-3 border-b px-4 py-3">{[["Unresolved",resolutionIntel.unresolved_items?.length],["Blocked",resolutionIntel.blocked?.length],["Waiting",resolutionIntel.waiting?.length],["Recheck",resolutionIntel.recheck_required?.length]].map(([label,count])=><div key={label}><b className="text-xl">{count||0}</b><div className="text-xs text-gray-500">{label}</div></div>)}</div>{resolutionFocus.length?<ol className="divide-y px-4">{resolutionFocus.map((x,i)=><li key={x.intelligence_id} className="py-3 text-sm"><div className="flex flex-wrap items-center gap-2"><b>{i+1}. {x.priority_tier}</b><State value={x.state}/><Badge tone="gray">{x.reason_class.replaceAll("_"," ")}</Badge></div><p className="mt-1">{x.why}</p><p className="mt-1 text-xs text-gray-600"><b>Resolves when:</b> {x.what_would_resolve_this}</p><p className="mt-1 text-xs text-blue-700"><b>Next:</b> {x.safe_next_steps?.[0]?.label||"No supported action is currently available."}</p><small>{x.time_in_state_label} in state · {x.evidence_ids.join(" · ")}</small></li>)}</ol>:<p className="p-4 text-sm text-gray-500">No unresolved resolution records.</p>}</Card>
      <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
        <Card><CardHeader title="Attention" subtitle="Current blockers, issues, and unverified owner state; stable IDs prevent double-counting."/><div className="grid grid-cols-3 gap-3 border-b px-4 py-3">{["blocker","issue","unverified"].map(k=><div key={k}><b className="text-xl">{center.attention?.counts?.[k]||0}</b><div className="text-xs capitalize text-gray-500">{k}</div></div>)}</div><ul className="divide-y px-4">{(center.attention?.items||[]).slice(0,7).map(x=><li key={x.id} className="py-2 text-sm"><State value={x.priority}/> <span className="ml-2">{x.title}</span><small>{x.domain} · ATTN-{x.id}</small></li>)}</ul>{!(center.attention?.items||[]).length&&<p className="p-4 text-sm text-gray-500">No current attention items recorded.</p>}</Card>
        <Card className="border-violet-200 bg-violet-50/40"><div className="p-4"><h2 className="flex items-center gap-2 font-semibold text-violet-950"><Bot size={18}/> Grounded AI Copilot</h2><p className="mt-1 text-xs text-violet-700">Deterministic evidence first. AI advises and cites; it cannot execute, approve, accept, or resolve.</p><div className="mt-3 flex flex-wrap gap-2">{QUERIES.map(([type,label])=><button key={type} onClick={()=>{setQueryType(type);ask(type);}} disabled={busy} className="rounded-full border border-violet-200 bg-white px-2.5 py-1 text-xs text-violet-800">{label}</button>)}</div><form onSubmit={e=>{e.preventDefault();ask();}} className="mt-3 flex gap-2"><label className="sr-only" htmlFor="copilot-question">Project question</label><input id="copilot-question" value={question} onChange={e=>setQuestion(e.target.value)} className="min-w-0 flex-1 rounded border px-3 py-2 text-sm"/><button disabled={busy} className="inline-flex items-center gap-1 rounded bg-violet-700 px-3 py-2 text-sm text-white"><Send size={13}/> Ask</button></form>{busy&&<p className="mt-3 text-sm">Checking current evidence…</p>}{copilot&&!busy?<CopilotAnswer result={copilot} evidence={evidence}/>:!busy&&<button onClick={()=>ask("FOCUS_TODAY")} className="mt-3 rounded bg-violet-700 px-3 py-2 text-sm text-white">What should I focus on today?</button>}</div></Card>
      </div>
      <section><h2 className="mb-2 font-semibold">Active Work</h2><div className="grid gap-4 lg:grid-cols-3"><Summary title="Recent Changes" items={(center.recent_changes||[]).slice(0,5)} empty="No recorded recent changes." render={x=><><div>{x.summary}</div><small>{formatDateTime(x.timestamp)} · CHG-{x.change_id}</small></>} link={`/projects/${project.id}/history`}/><Summary title="Impacts" items={(center.active_impacts||[]).slice(0,5)} empty="No reviewed impact relationships." render={x=><><State value={x.human_review_status}/> <span>{x.origin_relationship?.target_type||x.relationship_id}</span><small>IMP-{x.confirmation_id} · {x.relationship_class_at_review}</small></>} link={`/projects/${project.id}/deliverables`}/><Summary title="Actions" items={routes.slice(0,5)} empty="No routed actions." render={x=><><State value={x.status}/> <span>{x.action_type.replaceAll("_"," ")}</span><small>{x.target_service} · ACT-{x.action_route_id}</small></>} link={`/projects/${project.id}/deliverables`}/></div></section>
      <div className="grid gap-4 lg:grid-cols-2"><Summary title="Open / Waiting Resolution" items={active.slice(0,7)} empty="No active resolution records." render={x=><><State value={x.resolution_state}/> <span>{x.resolution_reason}</span><small>{x.evaluation_rule_id} · RES-{x.resolution_id}</small></>} link={`/projects/${project.id}/deliverables`}/><Card><CardHeader title="Waiting On" subtitle="Only responsibility identified by current evidence"/><div className="grid grid-cols-2 gap-3 p-4">{Object.entries(center.waiting_on||{}).map(([owner,count])=><div key={owner} className="rounded border p-3"><b className="text-lg">{count}</b><div className="text-xs text-gray-500">{owner.replaceAll("_"," ")}</div></div>)}{!Object.keys(center.waiting_on||{}).length&&<p className="col-span-2 text-sm text-gray-500">No deterministic waiting owner identified.</p>}</div></Card></div>
      <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader title="Governance & Acceptance" subtitle="TEST and INTERNAL evidence never imply CUSTOMER acceptance"/><div className="space-y-2 p-4 text-sm"><div>{center.governance.flag_count} current governance flag(s)</div><div><State value={center.acceptance.customer_accepted?"CUSTOMER ACCEPTED":"NOT RECORDED"}/> Customer acceptance</div>{(center.governance.flags||[]).slice(0,4).map(x=><div key={x.instance_id} className="border-t pt-2">{x.human_code}: {x.readiness} · {x.freshness}</div>)}<Link to={`/projects/${project.id}/deliverables`} className="inline-flex items-center gap-1 text-blue-700">Review documents <ArrowRight size={12}/></Link></div></Card><Summary title="Recently Resolved" items={resolved.slice(0,5)} empty="No recently resolved impacts." render={x=><><State value={x.resolution_state}/> <span>{x.resolution_reason}</span><small>{formatDateTime(x.evaluated_at)} · RES-{x.resolution_id}</small></>} link={`/projects/${project.id}/history`}/></div>
      <p className="text-[11px] text-gray-400">{center.contract_version} · {center.freshness.overall} · {center.performance.command_center_latency_ms} ms · {center.performance.downstream_calls} owner calls · generated {formatDateTime(center.provenance.generated_at)}</p>
    </>}
  </main>;
}

function Summary({title,items,empty,render,link}) { return <Card><CardHeader title={title} right={<Link to={link} className="text-xs text-gray-500">Open context →</Link>}/><div className="px-4 pb-3">{items.length?<ul className="divide-y">{items.map((x,i)=><li key={x.resolution_id||x.action_route_id||x.confirmation_id||x.change_id||i} className="py-2 text-xs text-gray-700">{render(x)}</li>)}</ul>:<p className="py-3 text-sm text-gray-500">{empty}</p>}</div></Card>; }
function Briefing({brief,onReviewed,busy}) { const sections=[["New Since Last Review",brief.new_attention],["Still Open",brief.still_open],["Waiting On",brief.waiting_on],["Resolved Since Last Review",brief.resolved_since_review],["Reopened",brief.reopened]]; return <section aria-labelledby="daily-brief-title"><Card className="border-blue-200 bg-blue-50/30"><div className="flex flex-wrap items-start justify-between gap-3 border-b border-blue-100 p-4"><div><h2 id="daily-brief-title" className="font-semibold text-blue-950">{brief.briefing_mode==="SINCE_LAST_REVIEW"?"Since Your Last Review":"Current Project Brief"}</h2><p className="mt-1 text-xs text-blue-700">{brief.briefing_window.from?`${formatDateTime(brief.briefing_window.from)} → ${formatDateTime(brief.briefing_window.to)}`:`First view · through ${formatDateTime(brief.briefing_window.to)}`}</p></div><button onClick={onReviewed} disabled={busy} className="rounded bg-blue-700 px-3 py-2 text-sm text-white disabled:opacity-50">Mark Reviewed</button></div><div className="grid gap-4 p-4 lg:grid-cols-[.8fr_1.2fr]"><div><h3 className="text-xs font-semibold uppercase text-blue-900">Focus Today</h3><ol className="mt-2 space-y-2">{(brief.deterministic_focus||[]).map((x,i)=><li key={x.briefing_item_id} className="text-sm"><b>{i+1}. {x.priority}</b> · {x.title}<div className="text-[10px] text-gray-500">{x.time_classification} · {x.evidence_ids.join(" · ")}</div></li>)}</ol>{!brief.deterministic_focus?.length&&<p className="mt-2 text-sm text-gray-500">No current focus items recorded.</p>}</div><div className="grid gap-3 sm:grid-cols-2">{sections.map(([title,items])=><details key={title} open={title==="New Since Last Review"||title==="Still Open"} className="rounded border bg-white p-2"><summary className="cursor-pointer text-xs font-semibold">{title} ({items?.length||0})</summary><ul className="mt-2 space-y-1 text-xs">{(items||[]).map(x=><li key={x.briefing_item_id}><State value={x.state}/> {x.title}</li>)}</ul></details>)}</div></div>{brief.limitations?.length>0&&<div className="border-t px-4 py-2 text-xs text-amber-700">{brief.limitations.join(" · ")}</div>}</Card></section>; }
function CopilotAnswer({result,evidence}) { return <div className="mt-3 rounded border border-violet-200 bg-white p-3 text-sm"><div><State value={result.status}/> <span>{result.answer||result.message}</span></div>{result.status==="NOT_CONFIGURED"&&<p className="mt-1 text-xs text-gray-500">AI is not configured; the grounded list below remains available.</p>}<ol className="mt-2 space-y-2">{(result.focus_items||[]).map((x,i)=><li key={i}><b>{i+1}. {x.title}</b><div>{x.why}</div><div className="mt-1 flex flex-wrap gap-1">{x.evidence_ids.map(id=><details key={id} className="rounded bg-violet-50 px-1.5 text-[10px]"><summary className="cursor-pointer text-violet-800">[{id}]</summary><div className="w-64 py-1"><b>{evidence[id]?.source_label}</b>: {evidence[id]?.summary||"Citation unavailable"}</div></details>)}</div>{x.action_type&&<Link to="../deliverables" className="text-xs text-blue-700">Review Action →</Link>}</li>)}</ol>{(result.limitations||[]).map(x=><p key={x} className="mt-2 text-xs text-amber-700">Limitation: {x}</p>)}<p className="mt-2 flex items-center gap-1 text-[10px] text-gray-400"><ShieldCheck size={11}/> No automatic execution · AI authority: none</p></div>; }
