"""
IaC Configuration Renderer for INFRA-AGAIN.

Deterministically generates OpenTofu HCL from an InfrastructurePlan.
No LLM-generated arbitrary HCL — controlled templates only.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from ..core.domain import InfrastructurePlan, Provider


def render_tofu_config(
    plan: InfrastructurePlan,
    work_dir: Path,
    *,
    run_id: str = "",
    correlation_id: str = "",
    endpoint: str = "http://localhost:4566",
    region: str = "us-east-1",
) -> str:
    """Generate OpenTofu HCL files in work_dir. Returns configuration checksum."""
    work_dir.mkdir(parents=True, exist_ok=True)

    resources_hcl = _render_resources(plan, run_id, correlation_id)
    providers_hcl = _render_providers(endpoint, region)
    outputs_hcl = _render_outputs(plan)

    main_content = f"""# Generated by INFRA-AGAIN — do not edit manually
# Run ID: {run_id}
# Correlation ID: {correlation_id}

{providers_hcl}

{resources_hcl}
"""
    (work_dir / "main.tf").write_text(main_content)

    if outputs_hcl:
        (work_dir / "outputs.tf").write_text(outputs_hcl)

    # Compute checksum of all generated files
    checksum = hashlib.sha256()
    for tf_file in sorted(work_dir.glob("*.tf")):
        checksum.update(tf_file.read_bytes())
    return checksum.hexdigest()[:16]


def _render_providers(endpoint: str, region: str) -> str:
    """Render AWS provider block with fakecloud endpoints — no real AWS fallback."""
    return f"""terraform {{
  required_version = ">= 1.6.0"
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

provider "aws" {{
  region = "{region}"

  # FAKECLOUD — all endpoints routed to local simulator
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  # Force path-style S3 addressing for fakecloud compatibility
  s3_use_path_style           = true

  endpoints {{
    s3 = "{endpoint}"
  }}

  # Dummy credentials for provider requirement
  access_key = "test"
  secret_key = "test"
}}
"""


def _render_resources(plan: InfrastructurePlan, run_id: str, correlation_id: str) -> str:
    """Render resources from capability mappings."""
    blocks: list[str] = []

    for i, mapping in enumerate(plan.capability_mappings):
        if mapping.resource_type == "AWS::S3::Bucket":
            bucket_name = mapping.resource_properties.get(
                "bucket_name", f"infra-again-{run_id[:8]}"
            )
            blocks.append(f"""resource "aws_s3_bucket" "bucket_{i}" {{
  bucket = "{bucket_name}"

  tags = {{
    managed_by    = "INFRA_AGAIN"
    run_id        = "{run_id}"
    correlation_id = "{correlation_id}"
    ephemeral     = "true"
  }}
}}
""")
        elif mapping.resource_type == "AWS::S3::Object":
            bucket = mapping.resource_properties.get("bucket", "")
            key = mapping.resource_properties.get("key", "test-object")
            body = mapping.resource_properties.get("body", "hello-again")
            blocks.append(f"""resource "aws_s3_object" "object_{i}" {{
  bucket  = "{bucket}"
  key     = "{key}"
  content = "{body}"

  tags = {{
    managed_by     = "INFRA_AGAIN"
    run_id         = "{run_id}"
    correlation_id = "{correlation_id}"
    ephemeral      = "true"
  }}
}}
""")

    return "\n".join(blocks)


def _render_outputs(plan: InfrastructurePlan) -> str:
    """Render outputs for created resources."""
    lines: list[str] = []
    for i, mapping in enumerate(plan.capability_mappings):
        if mapping.resource_type == "AWS::S3::Bucket":
            lines.append(f"""output "bucket_{i}_name" {{
  value = aws_s3_bucket.bucket_{i}.bucket
}}
""")
    return "\n".join(lines)
