"""p0 initial schema

Revision ID: 1286f0e54ef1
Revises: 
Create Date: 2026-08-16 04:17:57.177164
"""
from alembic import op
import sqlalchemy as sa


revision = '1286f0e54ef1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('api_endpoints',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('semantic_id', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('request_spec', sa.JSON(), nullable=True),
    sa.Column('response_spec', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semantic_id')
    )
    with op.batch_alter_table('api_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_endpoints_project_id'), ['project_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.Enum('REQUIREMENT_REGISTER', 'UR', 'DR', 'DATABASE_SCHEMA', 'ER_DIAGRAM', 'DATA_DICTIONARY', 'PROCESS_FLOW', 'ARCHITECTURE', 'API_DESIGN', 'WHITEBOARD', 'NOTE', 'CHANGE_REQUEST', 'DECISION', name='artifacttype'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('current_draft_revision_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['current_draft_revision_id'], ['artifact_revisions.id'], name='fk_artifact_current_draft', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_project_id'), ['project_id'], unique=False)

    op.create_table('assumptions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('semantic_id', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semantic_id')
    )
    with op.batch_alter_table('assumptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assumptions_project_id'), ['project_id'], unique=False)

    op.create_table('baselines',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baselines_project_id'), ['project_id'], unique=False)

    op.create_table('change_requests',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_change', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACCEPTED', 'IMPLEMENTED', 'REJECTED', 'DEFERRED', name='changerequeststatus'), nullable=False),
    sa.Column('target_release', sa.String(length=60), nullable=True),
    sa.Column('schedule_impact', sa.String(length=300), nullable=True),
    sa.Column('commercial_impact', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_requests_project_id'), ['project_id'], unique=False)

    op.create_table('clarifications',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('asked_by', sa.String(length=100), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clarifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clarifications_project_id'), ['project_id'], unique=False)

    op.create_table('comment_threads',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_threads_project_id'), ['project_id'], unique=False)

    op.create_table('database_schemas',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('semantic_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semantic_id')
    )
    with op.batch_alter_table('database_schemas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_database_schemas_project_id'), ['project_id'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('semantic_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=100), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supersedes_semantic_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semantic_id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_project_id'), ['project_id'], unique=False)

    op.create_table('process_flows',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('semantic_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semantic_id')
    )
    with op.batch_alter_table('process_flows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_flows_project_id'), ['project_id'], unique=False)

    op.create_table('requirements',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=60), nullable=True),
    sa.Column('source_reference', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'CONFIRMED', 'SUPERSEDED', name='requirementstatus'), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_project_id'), ['project_id'], unique=False)

    op.create_table('semantic_objects',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('semantic_id', sa.String(length=200), nullable=False),
    sa.Column('object_type', sa.Enum('REQUIREMENT', 'DOCUMENT_SECTION', 'DB_SCHEMA', 'DB_TABLE', 'DB_FIELD', 'DB_RELATION', 'PROCESS_FLOW', 'PROCESS_STEP', 'API_ENDPOINT', 'ARCHITECTURE_NODE', 'SCREEN', name='semanticobjecttype'), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('entity_ref', sa.String(length=40), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'semantic_id')
    )
    with op.batch_alter_table('semantic_objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semantic_objects_project_id'), ['project_id'], unique=False)

    op.create_table('trace_links',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('source_semantic_id', sa.String(length=200), nullable=False),
    sa.Column('target_semantic_id', sa.String(length=200), nullable=False),
    sa.Column('relation_type', sa.Enum('DERIVED_FROM', 'IMPLEMENTS', 'DESIGNED_BY', 'VALIDATED_BY', 'AFFECTS', 'REFERENCES', 'SUPERSEDES', 'GENERATED_FROM', 'CONFIRMED_BY', name='tracerelationtype'), nullable=False),
    sa.Column('revision_context', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source_semantic_id', 'target_semantic_id', 'relation_type')
    )
    with op.batch_alter_table('trace_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trace_links_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trace_links_source_semantic_id'), ['source_semantic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trace_links_target_semantic_id'), ['target_semantic_id'], unique=False)

    op.create_table('artifact_revisions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('artifact_id', sa.String(length=40), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'CONFIRMED', 'SUPERSEDED', 'ARCHIVED', name='revisionstatus'), nullable=False),
    sa.Column('based_on_revision_id', sa.String(length=40), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['based_on_revision_id'], ['artifact_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'revision_number')
    )
    with op.batch_alter_table('artifact_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_revisions_artifact_id'), ['artifact_id'], unique=False)

    op.create_table('change_request_links',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('change_request_id', sa.String(length=40), nullable=False),
    sa.Column('semantic_id', sa.String(length=200), nullable=False),
    sa.Column('link_type', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_request_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_request_links_change_request_id'), ['change_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_request_links_semantic_id'), ['semantic_id'], unique=False)

    op.create_table('database_relations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('schema_id', sa.String(length=40), nullable=False),
    sa.Column('semantic_id', sa.String(length=200), nullable=False),
    sa.Column('from_field_semantic_id', sa.String(length=200), nullable=False),
    sa.Column('to_field_semantic_id', sa.String(length=200), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schema_id'], ['database_schemas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('database_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_database_relations_schema_id'), ['schema_id'], unique=False)

    op.create_table('database_tables',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('schema_id', sa.String(length=40), nullable=False),
    sa.Column('semantic_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schema_id'], ['database_schemas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_id', 'semantic_id')
    )
    with op.batch_alter_table('database_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_database_tables_schema_id'), ['schema_id'], unique=False)

    op.create_table('process_steps',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('flow_id', sa.String(length=40), nullable=False),
    sa.Column('semantic_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('step_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['process_flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('process_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_steps_flow_id'), ['flow_id'], unique=False)

    op.create_table('releases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=60), nullable=False),
    sa.Column('baseline_id', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_releases_project_id'), ['project_id'], unique=False)

    op.create_table('annotations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('artifact_revision_id', sa.String(length=40), nullable=True),
    sa.Column('anchor_object_type', sa.String(length=60), nullable=False),
    sa.Column('anchor_semantic_id', sa.String(length=200), nullable=False),
    sa.Column('canvas_x', sa.Float(), nullable=True),
    sa.Column('canvas_y', sa.Float(), nullable=True),
    sa.Column('type', sa.Enum('COMMENT', 'QUESTION', 'CLARIFICATION', 'DECISION', 'ASSUMPTION', 'ISSUE', 'CHANGE_REQUEST', name='annotationtype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('drawing_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'REPLIED', 'RESOLVED', 'REOPENED', name='annotationstatus'), nullable=False),
    sa.Column('thread_id', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_revision_id'], ['artifact_revisions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['comment_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotations_anchor_semantic_id'), ['anchor_semantic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_artifact_revision_id'), ['artifact_revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_thread_id'), ['thread_id'], unique=False)

    op.create_table('baseline_bindings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('baseline_id', sa.String(length=40), nullable=False),
    sa.Column('artifact_id', sa.String(length=40), nullable=False),
    sa.Column('artifact_revision_id', sa.String(length=40), nullable=False),
    sa.Column('semantic_object_id', sa.String(length=200), nullable=True),
    sa.Column('semantic_object_type', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['artifact_revision_id'], ['artifact_revisions.id'], ),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('baseline_id', 'artifact_id')
    )
    with op.batch_alter_table('baseline_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baseline_bindings_baseline_id'), ['baseline_id'], unique=False)

    op.create_table('confirmations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('artifact_revision_id', sa.String(length=40), nullable=False),
    sa.Column('confirmed_by', sa.String(length=100), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_revision_id'], ['artifact_revisions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_confirmations_artifact_revision_id'), ['artifact_revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_confirmations_project_id'), ['project_id'], unique=False)

    op.create_table('database_fields',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('table_id', sa.String(length=40), nullable=False),
    sa.Column('semantic_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=False),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('default', sa.String(length=200), nullable=True),
    sa.Column('primary_key', sa.Boolean(), nullable=False),
    sa.Column('foreign_key', sa.Boolean(), nullable=False),
    sa.Column('reference', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['database_tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'semantic_id')
    )
    with op.batch_alter_table('database_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_database_fields_table_id'), ['table_id'], unique=False)
        batch_op.create_index('ix_db_fields_table', ['table_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('artifact_revision_id', sa.String(length=40), nullable=False),
    sa.Column('reviewer', sa.String(length=100), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_revision_id'], ['artifact_revisions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_artifact_revision_id'), ['artifact_revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_project_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_artifact_revision_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('database_fields', schema=None) as batch_op:
        batch_op.drop_index('ix_db_fields_table')
        batch_op.drop_index(batch_op.f('ix_database_fields_table_id'))

    op.drop_table('database_fields')
    with op.batch_alter_table('confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_confirmations_project_id'))
        batch_op.drop_index(batch_op.f('ix_confirmations_artifact_revision_id'))

    op.drop_table('confirmations')
    with op.batch_alter_table('baseline_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baseline_bindings_baseline_id'))

    op.drop_table('baseline_bindings')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotations_thread_id'))
        batch_op.drop_index(batch_op.f('ix_annotations_project_id'))
        batch_op.drop_index(batch_op.f('ix_annotations_artifact_revision_id'))
        batch_op.drop_index(batch_op.f('ix_annotations_anchor_semantic_id'))

    op.drop_table('annotations')
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_releases_project_id'))

    op.drop_table('releases')
    with op.batch_alter_table('process_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_steps_flow_id'))

    op.drop_table('process_steps')
    with op.batch_alter_table('database_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_database_tables_schema_id'))

    op.drop_table('database_tables')
    with op.batch_alter_table('database_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_database_relations_schema_id'))

    op.drop_table('database_relations')
    with op.batch_alter_table('change_request_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_request_links_semantic_id'))
        batch_op.drop_index(batch_op.f('ix_change_request_links_change_request_id'))

    op.drop_table('change_request_links')
    with op.batch_alter_table('artifact_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_revisions_artifact_id'))

    op.drop_table('artifact_revisions')
    with op.batch_alter_table('trace_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trace_links_target_semantic_id'))
        batch_op.drop_index(batch_op.f('ix_trace_links_source_semantic_id'))
        batch_op.drop_index(batch_op.f('ix_trace_links_project_id'))

    op.drop_table('trace_links')
    with op.batch_alter_table('semantic_objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semantic_objects_project_id'))

    op.drop_table('semantic_objects')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_project_id'))

    op.drop_table('requirements')
    with op.batch_alter_table('process_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_flows_project_id'))

    op.drop_table('process_flows')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_project_id'))

    op.drop_table('decisions')
    with op.batch_alter_table('database_schemas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_database_schemas_project_id'))

    op.drop_table('database_schemas')
    with op.batch_alter_table('comment_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_threads_project_id'))

    op.drop_table('comment_threads')
    with op.batch_alter_table('clarifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clarifications_project_id'))

    op.drop_table('clarifications')
    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_requests_project_id'))

    op.drop_table('change_requests')
    with op.batch_alter_table('baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baselines_project_id'))

    op.drop_table('baselines')
    with op.batch_alter_table('assumptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assumptions_project_id'))

    op.drop_table('assumptions')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_project_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('api_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_endpoints_project_id'))

    op.drop_table('api_endpoints')
    op.drop_table('projects')
    # ### end Alembic commands ###
