"""7-sheet Excel workbook — rebuild prompt §17. Columns match the spec
exactly (02_Test_Results' 19 columns are quoted verbatim from the spec).
No embedded thumbnails in 04_Evidence_Index — same no-Pillow decision as
Phase 5; evidence is referenced by ID/hash/caption instead, with the
full image available in the portable ZIP package.
"""

import io
import json
from datetime import datetime, timezone

import openpyxl
from openpyxl.utils import get_column_letter

from . import models
from .metrics import result_counts, pass_rate, evidence_completeness


def evidence_code(evidence_id: int) -> str:
    return f"EVID-{evidence_id}"


def _autosize(ws):
    for col_cells in ws.columns:
        length = max((len(str(c.value)) if c.value is not None else 0) for c in col_cells)
        ws.column_dimensions[get_column_letter(col_cells[0].column)].width = min(max(length + 2, 10), 60)


def build_workbook(db, project: models.Project, cycle: models.TestCycle, generated_by: str) -> openpyxl.Workbook:
    wb = openpyxl.Workbook()
    wb.remove(wb.active)

    revision = db.query(models.ScriptRevision).filter(models.ScriptRevision.id == cycle.script_revision_id).first()
    suite = db.query(models.TestSuite).filter(models.TestSuite.id == cycle.suite_id).first()

    cases_by_result = {
        r.id: c
        for r, c in (
            db.query(models.CycleTestResult, models.TestCase)
            .join(models.TestCase, models.TestCase.id == models.CycleTestResult.test_case_id)
            .filter(models.CycleTestResult.cycle_id == cycle.id)
            .all()
        )
    }
    results = (
        db.query(models.CycleTestResult)
        .filter(models.CycleTestResult.cycle_id == cycle.id)
        .order_by(models.CycleTestResult.id)
        .all()
    )

    # ---------- 00_Cover ----------
    ws = wb.create_sheet("00_Cover")
    now = datetime.now(timezone.utc)
    for row in [
        ("Application/Project", project.name),
        ("Suite", suite.name if suite else None),
        ("Script Revision", revision.revision_label if revision else None),
        ("Cycle", cycle.name),
        ("Environment", cycle.environment),
        ("Release Version", cycle.release_version),
        ("Target URL", cycle.target_base_url),
        ("Execution Period Start", cycle.started_at),
        ("Execution Period End", cycle.finished_at),
        ("Generated By", generated_by),
        ("Generated Timestamp (UTC)", now.strftime("%Y-%m-%d %H:%M:%S UTC")),
        ("Report Version", "1.0"),
    ]:
        ws.append(row)
    _autosize(ws)

    # ---------- 01_Execution_Summary ----------
    ws = wb.create_sheet("01_Execution_Summary")
    counts = result_counts(db, cycle.id)
    pr = pass_rate(db, cycle.id)
    ec = evidence_completeness(db, cycle.id)
    ws.append(["Status", "Count", "Definition"])
    definitions = {
        "PASS": "Case executed and met its expected result.",
        "FAIL": "Case executed and did not meet its expected result (shown as NG in the UI).",
        "BLOCKED": "Case could not be executed; blocked_reason is required.",
        "NOT_RUN": "Case has not been executed yet.",
        "NOT_APPLICABLE": "Case does not apply this cycle; na_reason required, admin approval required.",
    }
    for status in models.RESULT_STATUSES:
        ws.append([status, counts[status], definitions[status]])
    ws.append([])
    ws.append(["Pass Rate", f"{pr['percent']}%", pr["formula"]])
    ws.append(["Evidence Completeness", f"{ec['percent']}%", ec["formula"]])
    _autosize(ws)

    # ---------- 02_Test_Results ----------
    ws = wb.create_sheet("02_Test_Results")
    ws.append(
        [
            "Sequence",
            "Test ID",
            "Title",
            "Priority",
            "Traceability",
            "Fixture",
            "Environment",
            "Setup",
            "Action",
            "Validation",
            "Expected Result",
            "Actual Result",
            "Status",
            "Tester",
            "Executed Date",
            "Reviewer",
            "Review Status",
            "Defect ID",
            "Evidence Count",
            "Evidence Reference",
        ]
    )
    for result in results:
        case = cases_by_result.get(result.id)
        if not case:
            continue
        evidence_items = (
            db.query(models.EvidenceItem)
            .filter(models.EvidenceItem.cycle_test_result_id == result.id, models.EvidenceItem.status == "ACTIVE")
            .all()
        )
        ws.append(
            [
                case.sequence_no,
                case.checkpoint_code,
                case.title,
                case.priority,
                case.traceability_md,
                case.fixture_md,
                case.environment_md,
                case.setup_md,
                case.action_md,
                case.validation_md,
                case.expected_result_md,
                result.actual_result_md,
                result.status,
                result.executed_by,
                result.executed_at.strftime("%Y-%m-%d %H:%M:%S") if result.executed_at else None,
                result.reviewed_by,
                result.review_status,
                result.defect_reference,
                len(evidence_items),
                ", ".join(evidence_code(e.id) for e in evidence_items),
            ]
        )
    _autosize(ws)

    # ---------- 03_NG_Defects ----------
    ws = wb.create_sheet("03_NG_Defects")
    ws.append(["Test ID", "Title", "Severity", "Defect Status", "Actual Result", "Callout Summary", "Evidence Reference"])
    defects_by_result = {}
    for d in db.query(models.Defect).filter(models.Defect.cycle_id == cycle.id).all():
        if d.cycle_test_result_id:
            defects_by_result.setdefault(d.cycle_test_result_id, []).append(d)
    for result in results:
        if result.status != "FAIL":
            continue
        case = cases_by_result.get(result.id)
        if not case:
            continue
        linked_defects = defects_by_result.get(result.id, [])
        evidence_items = (
            db.query(models.EvidenceItem)
            .filter(models.EvidenceItem.cycle_test_result_id == result.id, models.EvidenceItem.status == "ACTIVE")
            .all()
        )
        callout_summary = _callout_summary(db, evidence_items)
        ws.append(
            [
                case.checkpoint_code,
                case.title,
                linked_defects[0].severity if linked_defects else "UNSPECIFIED",
                linked_defects[0].status if linked_defects else None,
                result.actual_result_md,
                callout_summary,
                ", ".join(evidence_code(e.id) for e in evidence_items),
            ]
        )
    _autosize(ws)

    # ---------- 04_Evidence_Index ----------
    ws = wb.create_sheet("04_Evidence_Index")
    ws.append(
        ["Evidence ID", "Test ID", "Caption", "Captured By", "Captured Date", "Original SHA-256", "Annotation Revision", "Callout Summary", "Package Reference"]
    )
    all_evidence = db.query(models.EvidenceItem).filter(models.EvidenceItem.cycle_id == cycle.id).all()
    for e in all_evidence:
        case = cases_by_result.get(e.cycle_test_result_id)
        callout_summary = _callout_summary(db, [e])
        ws.append(
            [
                evidence_code(e.id),
                case.checkpoint_code if case else None,
                e.caption,
                e.captured_by,
                e.captured_at.strftime("%Y-%m-%d %H:%M:%S") if e.captured_at else None,
                e.original_sha256,
                e.current_revision_no,
                callout_summary,
                f"evidence/{case.checkpoint_code if case else 'unknown'}_{evidence_code(e.id)}",
            ]
        )
    _autosize(ws)

    # ---------- 05_Revision_History ----------
    ws = wb.create_sheet("05_Revision_History")
    ws.append(["Revision Label", "Status", "Source Filename", "Source SHA-256", "Change Summary", "Published By", "Published At", "Comparison Summary"])
    if suite:
        revisions = (
            db.query(models.ScriptRevision)
            .filter(models.ScriptRevision.suite_id == suite.id)
            .order_by(models.ScriptRevision.revision_number_sort)
            .all()
        )
        for i, rev in enumerate(revisions):
            comparison = "Initial revision" if i == 0 else f"Supersedes revision {revisions[i - 1].revision_label}" if rev.supersedes_revision_id else "—"
            ws.append(
                [
                    rev.revision_label,
                    rev.status,
                    rev.source_filename,
                    rev.source_sha256,
                    rev.change_summary,
                    rev.published_by,
                    rev.published_at.strftime("%Y-%m-%d %H:%M:%S") if rev.published_at else None,
                    comparison,
                ]
            )
    _autosize(ws)

    # ---------- 06_Sign_Off ----------
    ws = wb.create_sheet("06_Sign_Off")
    ws.append(["Sign-off Type", "Decision", "Actor", "Timestamp", "Comments"])
    for s in db.query(models.SignOff).filter(models.SignOff.cycle_id == cycle.id).order_by(models.SignOff.acted_at).all():
        ws.append([s.signoff_type, s.decision, s.actor, s.acted_at.strftime("%Y-%m-%d %H:%M:%S"), s.comment_md])
    _autosize(ws)

    return wb


def _callout_summary(db, evidence_items: list[models.EvidenceItem]) -> str:
    parts = []
    for e in evidence_items:
        if e.current_revision_no == 0:
            continue
        latest = (
            db.query(models.EvidenceRevision)
            .filter(models.EvidenceRevision.evidence_id == e.id)
            .order_by(models.EvidenceRevision.revision_no.desc())
            .first()
        )
        if not latest:
            continue
        try:
            shapes = json.loads(latest.annotation_json)
        except (TypeError, ValueError):
            continue
        callouts = sum(1 for s in shapes if s.get("type") == "callout")
        if shapes:
            parts.append(f"{evidence_code(e.id)}: {len(shapes)} annotation(s), {callouts} callout(s)")
    return "; ".join(parts)


def workbook_to_bytes(wb: openpyxl.Workbook) -> bytes:
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
